# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160604_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('opn', 'Open'), ('cls', 'Close')], default='opn', max_length=20),
        ),
    ]
